defaults:
  - setup: metaworld
  - experiment: collective_${defaults.0.setup}
  - worker: worker_sac
  - worker/components: ${defaults.0.setup}_actor
  - worker/components: ${defaults.0.setup}_critic
  - worker/components: ${defaults.0.setup}_encoder
  - worker/components: ${defaults.0.setup}_transition_model
  - worker/components: ${defaults.0.setup}_mask
  - worker/components: ${defaults.0.setup}_multitask
  - worker/components: ${defaults.0.setup}_gradnorm
  - worker/components: ${defaults.0.setup}_task_to_encoder_cluster
  - worker/optimizers: ${defaults.0.setup}_actor
  - worker/optimizers: ${defaults.0.setup}_alpha
  - worker/optimizers: ${defaults.0.setup}_critic
  - worker/optimizers: ${defaults.0.setup}_decoder
  - worker/optimizers: ${defaults.0.setup}_encoder
  
  - transformer_collective_network: transformer_collective_sac
  - transformer_collective_network/components: ${defaults.0.setup}_actor
  - transformer_collective_network/components: ${defaults.0.setup}_critic
  - transformer_collective_network/components: ${defaults.0.setup}_transformer_encoder
  - transformer_collective_network/components: ${defaults.0.setup}_world_model
  - transformer_collective_network/optimizers: ${defaults.0.setup}_actor
  - transformer_collective_network/optimizers: ${defaults.0.setup}_critic
  - transformer_collective_network/optimizers: ${defaults.0.setup}_alpha
  - transformer_collective_network/optimizers: ${defaults.0.setup}_transformer_encoder
  - transformer_collective_network/optimizers: ${defaults.0.setup}_world_model

  - student: student_sac
  - student/components: ${defaults.0.setup}_actor
  - student/components: ${defaults.0.setup}_critic
  - student/components: ${defaults.0.setup}_encoder
  - student/components: ${defaults.0.setup}_transition_model
  - student/components: ${defaults.0.setup}_mask
  - student/components: ${defaults.0.setup}_multitask
  - student/components: ${defaults.0.setup}_gradnorm
  - student/components: ${defaults.0.setup}_task_to_encoder_cluster
  - student/optimizers: ${defaults.0.setup}_actor
  - student/optimizers: ${defaults.0.setup}_alpha
  - student/optimizers: ${defaults.0.setup}_critic
  - student/optimizers: ${defaults.0.setup}_decoder
  - student/optimizers: ${defaults.0.setup}_encoder
  
  - env: ???
  - replay_buffer: mtrl
  - logger: mtrl
  - metrics: ${defaults.0.setup}
  - logbook: mtrl
project_root: ${env:PROJECT_ROOT}
