# @package _group_
# GPU Server optimized student SAC configuration

name: gpu_server_student_sac

encoder_feature_dim: 50
num_layers: 0 #4
num_filters: 0 #32

builder:
  _target_: mtrl.agent.sac.Agent
  # obs_shape
  # action_shape
  # device
  actor_cfg: ${student.actor}
  critic_cfg: ${student.critic}
  multitask_cfg: ${student.multitask}
  alpha_optimizer_cfg: ${student.optimizers.alpha}
  actor_optimizer_cfg: ${student.optimizers.actor}
  critic_optimizer_cfg: ${student.optimizers.critic}
  discount: 0.99
  init_temperature: 1.
  actor_update_freq: 1        # Increased from 1 (kept the same as it was already optimal)
  critic_tau: 0.005
  critic_target_update_freq: 1 # Increased from 2 for more frequent target updates
  encoder_tau: 0.05