# @package _group_
# GPU Server optimized worker SAC configuration
# Higher update frequencies and optimized parameters for multi-GPU servers

name: gpu_server_worker_sac

encoder_feature_dim: 50
num_layers: 0 #4
num_filters: 0 #32

builder:
  _target_: mtrl.agent.sac.Agent
  # obs_shape
  # action_shape
  # device
  actor_cfg: ${worker.actor}
  critic_cfg: ${worker.critic}
  multitask_cfg: ${worker.multitask}
  alpha_optimizer_cfg: ${worker.optimizers.alpha}
  actor_optimizer_cfg: ${worker.optimizers.actor}
  critic_optimizer_cfg: ${worker.optimizers.critic}
  discount: 0.99
  init_temperature: 1 #0.01 # 1
  actor_update_freq: 1  # Increased from 2 for more frequent updates with larger batches
  critic_tau: 0.005 # 0.01
  critic_target_update_freq: 1  # Increased from 2 for more frequent target updates
  encoder_tau: 0.05