# @package _group_.critic
# GPU Server optimized critic optimizer with adjusted learning rate for larger batch sizes

_target_: torch.optim.Adam
lr: 1e-3  # Increased from 3e-4 due to larger batch sizes (scale with sqrt(batch_size_ratio))
betas: [0.9, 0.999]